/*
 * Slock Backend
 *
 * This is the api doc for the Slock backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Data;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using api.db;
using MySql.Data.MySqlClient;
using System.Threading.Tasks;

namespace Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Rented : IEquatable<Rented>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public int Id { get; set; }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="userid")]
        public int UserId { get; set; }

        /// <summary>
        /// Gets or Sets lockId
        /// </summary>
        [DataMember(Name="lockid")]
        public int LockId { get; set; }

        /// <summary>
        /// Gets or Sets start
        /// </summary>
        [DataMember(Name="start")]
        public DateTime Start { get; set; }

        /// <summary>
        /// Gets or Sets end
        /// </summary>
        [DataMember(Name="end")]
        public DateTime End { get; set; }

        internal AppDb Db { get; set; }

        // Constructors
        internal Rented()
        {}

        internal Rented(AppDb db)
        {
            Db = db;
        }
        // end constructors

        public async Task InsertAsync()
        {
            using var cmd = Db.Connection.CreateCommand();
            cmd.CommandText = @"INSERT INTO `rented` (`user_id`, `lock_id`, `start`, `end`) VALUES (@owner_id, @lock_id, @start, @end);";
            BindParams(cmd);
            await cmd.ExecuteNonQueryAsync();
            Id = (int) cmd.LastInsertedId;
        }

        public async Task UpdateAsync()
        {
            using var cmd = Db.Connection.CreateCommand();
            cmd.CommandText = @"UPDATE `rented` SET `user_id` = @user_id, `lock_id` = @lock_id, `start` = @start, `end` = @end WHERE `id` = @id;";
            BindParams(cmd);
            BindId(cmd);
            await cmd.ExecuteNonQueryAsync();
        }

        private void BindId(MySqlCommand cmd)
        {
            cmd.Parameters.Add(new MySqlParameter
            {
                ParameterName = "@id",
                DbType = DbType.Int32,
                Value = Id,
            });
        }

        private void BindParams(MySqlCommand cmd)
        {
            cmd.Parameters.Add(new MySqlParameter
            {
                ParameterName = "@owner_id",
                DbType = DbType.String,
                Value = UserId,
            });
            cmd.Parameters.Add(new MySqlParameter
            {
                ParameterName = "@lock_id",
                DbType = DbType.String,
                Value = LockId,
            });
            cmd.Parameters.Add(new MySqlParameter
            {
                ParameterName = "@start",
                DbType = DbType.String,
                Value = Start,
            });
            cmd.Parameters.Add(new MySqlParameter
            {
                ParameterName = "@end",
                DbType = DbType.String,
                Value = End,
            });
        }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Rented {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  UserId: ").Append(UserId).Append("\n");
            // sb.Append("  RachetKey: ").Append(RachetKey).Append("\n");
            // sb.Append("  RatchetCounter: ").Append(RatchetCounter).Append("\n");
            // sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Rented)obj);
        }

        /// <summary>
        /// Returns true if Rented instances are equal
        /// </summary>
        /// <param name="other">Instance of Rented to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Rented other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return
                (
                    Id == other.Id
                ) && 
                (
                    UserId == other.UserId
                // ) && 
                // (
                //     Description == other.Description ||
                //     Description != null &&
                //     Description.Equals(other.Description)
                // ) && 
                // (
                //     RachetKey == other.RachetKey ||
                    // RachetKey != null &&
                    // RachetKey.Equals(other.RachetKey)
                // ) && 
                // (
                    // RatchetCounter == other.RatchetCounter //||
                    // RatchetCounter != null &&
                    // RatchetCounter.Equals(other.RatchetCounter)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    // if (RachetKey != null)
                    // hashCode = hashCode * 59 + RachetKey.GetHashCode();
                    // if (RatchetCounter != null)
                    // hashCode = hashCode * 59 + RatchetCounter.GetHashCode();
                    // if (Description != null)
                    // hashCode = hashCode * 59 + Description.GetHashCode();
                return hashCode;
            }
        }
        

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Rented left, Rented right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Rented left, Rented right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
