/*
 * Slock Backend
 *
 * This is the api doc for the Slock backend
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class RentedlocksInner : IEquatable<RentedlocksInner>
    { 
        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name="id")]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name="address")]
        public string Address { get; set; }

        /// <summary>
        /// Gets or Sets Description
        /// </summary>
        [DataMember(Name="description")]
        public string Description { get; set; }

        /// <summary>
        /// Gets or Sets AccessFromDate
        /// </summary>
        [DataMember(Name="accessFromDate")]
        public string AccessFromDate { get; set; }

        /// <summary>
        /// Gets or Sets AccessTillDate
        /// </summary>
        [DataMember(Name="accessTillDate")]
        public string AccessTillDate { get; set; }

        /// <summary>
        /// Gets or Sets Ownername
        /// </summary>
        [DataMember(Name="ownername")]
        public string Ownername { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class RentedlocksInner {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  Description: ").Append(Description).Append("\n");
            sb.Append("  AccessFromDate: ").Append(AccessFromDate).Append("\n");
            sb.Append("  AccessTillDate: ").Append(AccessTillDate).Append("\n");
            sb.Append("  Ownername: ").Append(Ownername).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((RentedlocksInner)obj);
        }

        /// <summary>
        /// Returns true if RentedlocksInner instances are equal
        /// </summary>
        /// <param name="other">Instance of RentedlocksInner to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(RentedlocksInner other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    Id == other.Id ||
                    Id != null &&
                    Id.Equals(other.Id)
                ) && 
                (
                    Address == other.Address ||
                    Address != null &&
                    Address.Equals(other.Address)
                ) && 
                (
                    Description == other.Description ||
                    Description != null &&
                    Description.Equals(other.Description)
                ) && 
                (
                    AccessFromDate == other.AccessFromDate ||
                    AccessFromDate != null &&
                    AccessFromDate.Equals(other.AccessFromDate)
                ) && 
                (
                    AccessTillDate == other.AccessTillDate ||
                    AccessTillDate != null &&
                    AccessTillDate.Equals(other.AccessTillDate)
                ) && 
                (
                    Ownername == other.Ownername ||
                    Ownername != null &&
                    Ownername.Equals(other.Ownername)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (Id != null)
                    hashCode = hashCode * 59 + Id.GetHashCode();
                    if (Address != null)
                    hashCode = hashCode * 59 + Address.GetHashCode();
                    if (Description != null)
                    hashCode = hashCode * 59 + Description.GetHashCode();
                    if (AccessFromDate != null)
                    hashCode = hashCode * 59 + AccessFromDate.GetHashCode();
                    if (AccessTillDate != null)
                    hashCode = hashCode * 59 + AccessTillDate.GetHashCode();
                    if (Ownername != null)
                    hashCode = hashCode * 59 + Ownername.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(RentedlocksInner left, RentedlocksInner right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(RentedlocksInner left, RentedlocksInner right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
